# -*- coding: utf-8 -*-
"""4352.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtLfFEBNN_B9OhfqmPSYkCKA0AnzJHKJ
"""

#Student grade Tracker
def calculate_gpa(average_grade):
    if average_grade >= 90:
        return 'A', 4.0
    elif average_grade >= 80:
        return 'B', 3.0
    elif average_grade >= 70:
        return 'C', 2.0
    elif average_grade >= 60:
        return 'D', 1.0
    else:
        return 'F', 0.0

def main():
    num_subjects = int(input("Enter the number of subjects or assignments: "))
    total_grade = 0

    for i in range(1, num_subjects + 1):
        subject_name = input(f"Enter name of subject/assignment {i}: ")
        grade = float(input(f"Enter grade for {subject_name}: "))
        total_grade += grade

    average_grade = total_grade / num_subjects
    letter_grade, gpa = calculate_gpa(average_grade)

    print("\nOverall Grade Summary:")
    print(f"Average Grade: {average_grade:.2f}")
    print(f"Letter Grade: {letter_grade}")
    print(f"GPA: {gpa:.2f}")
if __name__ == "__main__":
  main()